# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4951966f9baca1b24b05da58479db52f6bad234aa1bb5c2788f900a5f51181271e5195fc7541e1b34cc37387ae859c35a5eb2a7ab7c9a2d37337d30eda0e55c8

test:
  secret_key_base: e2fcce5f7aa1bc65781c23758122b4918fa5d571f8241cd553cd0f35bb768d3abfd3279231e8cf410f6048a167ee199b144a612b6f30e4f71031b25e02163594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
